CREATE DATABASE MATRIMONY;

CREATE TABLE ACCOUNT(
	ACC_ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(100) UNIQUE,
    PHONE_NUM VARCHAR(15) UNIQUE,
    PASSWORD VARCHAR(50) NOT NULL,
	NAME VARCHAR(50) ,
    PRESENT_ADDRESS VARCHAR(50) ,
    PERMANENT_ADDRESS VARCHAR(50) ,
    ABOUT VARCHAR(300) ,
    RELIGION VARCHAR(10),
    HEIGHT VARCHAR(5) ,
    MARITAL_STATUS VARCHAR(10),
	SEX VARCHAR(10) ,
	IMAGE BLOB,
	DOB DATE,
	BLOOD_GRP VARCHAR(5) NOT NULL,
	SKIN_TYPE VARCHAR(10) NOT NULL
);

CREATE TABLE CHAT(
	SENDER_ID INT,
	MSG_BODY VARCHAR(100),
	RECEIVER_ID INT ,
	SENT_TIME DATETIME,
	FOREIGN KEY (SENDER_ID) REFERENCES ACCOUNT(ACC_ID),
	FOREIGN KEY (RECEIVER_ID) REFERENCES ACCOUNT(ACC_ID)
);

CREATE TABLE EDUCATION(
	EDU_ID INT PRIMARY KEY,
	EXAM_NAME VARCHAR(10),
	EXAM_RESULT VARCHAR (10),
	PASSING_YEAR DATE,
	P_ID INT,
	FOREIGN KEY (P_ID) REFERENCES ACCOUNT(ACC_ID)
);

CREATE TABLE HOBBY(
	HOBBY_ID INT PRIMARY KEY AUTO_INCREMENT,
	HOBBY_NAME VARCHAR(20),
	HOBBY_DETAILS VARCHAR(300),
	P_ID INT ,
	FOREIGN KEY (P_ID) REFERENCES ACCOUNT(ACC_ID)
);

CREATE TABLE QUALIFICATION(
	WORK_ID INT AUTO_INCREMENT PRIMARY KEY,
	PRESENT_POS VARCHAR(20),
	COM_NAME VARCHAR(20),
	JOIN_DATE DATE ,
	RESIGN_DATE DATE NULL,
	P_ID INT ,
	FOREIGN KEY (P_ID) REFERENCES ACCOUNT(ACC_ID)
);

CREATE TABLE REQUEST(
	SENDER_ID INT ,
	RECEIVER_ID INT,
	STATUS BOOLEAN,
	SENT_TIME DATETIME,
	FOREIGN KEY (SENDER_ID) REFERENCES ACCOUNT(ACC_ID),
	FOREIGN KEY (RECEIVER_ID) REFERENCES ACCOUNT(ACC_ID)
);

CREATE TABLE FRIENDS(
    ACCEPTED_ID int,
    ACCEPTOR_ID int,
    FREINDSHIP datetime,
    FOREIGN KEY(ACCEPTED_ID) REFERENCES account(ACC_ID),
    FOREIGN KEY(ACCEPTOR_ID) REFERENCES account(ACC_ID)
)

ALTER TABLE `account` CHANGE `IMAGE` `IMAGE` VARCHAR(200) NULL DEFAULT NULL;